# Generated by Django 4.1.3 on 2022-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
    ]
